import java.util.*;

class Solution {

    public List<Integer> diffWaysToCompute(String expression) {

            List<Integer> result = new ArrayList<>();

                    // Try every operator as a split point
                            for (int i = 0; i < expression.length(); i++) {

                                        char ch = expression.charAt(i);

                                                    if (ch == '+' || ch == '-' || ch == '*') {

                                                                    // Left side
                                                                                    String left = expression.substring(0, i);

                                                                                                    // Right side
                                                                                                                    String right = expression.substring(i + 1);

                                                                                                                                    // Recursively calculate both sides
                                                                                                                                                    List<Integer> leftResults = diffWaysToCompute(left);
                                                                                                                                                                    List<Integer> rightResults = diffWaysToCompute(right);

                                                                                                                                                                                    // Combine every possible result
                                                                                                                                                                                                    for (int l : leftResults) {
                                                                                                                                                                                                                        for (int r : rightResults) {

                                                                                                                                                                                                                                                if (ch == '+') {
                                                                                                                                                                                                                                                                            result.add(l + r);
                                                                                                                                                                                                                                                                                                    } 
                                                                                                                                                                                                                                                                                                                            else if (ch == '-') {
                                                                                                                                                                                                                                                                                                                                                        result.add(l - r);
                                                                                                                                                                                                                                                                                                                                                                                } 
                                                                                                                                                                                                                                                                                                                                                                                                        else {
                                                                                                                                                                                                                                                                                                                                                                                                                                    result.add(l * r);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // If there is no operator, expression is just a number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (result.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result.add(Integer.parseInt(expression));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return result;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }